# Generated by Django 4.0.6 on 2023-12-24 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('plan_type', models.CharField(choices=[('limited', 'Limited'), ('unlimited', 'Unlimited')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('activities', models.ManyToManyField(related_name='plans', to='activity.activity')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.site')),
            ],
        ),
        migrations.CreateModel(
            name='PlanPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('sessions_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('price_unit', models.CharField(choices=[('ARS', 'Argentine Peso'), ('USD', 'US Dollar'), ('EUR', 'Euro')], max_length=50)),
                ('price_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
            ],
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_left', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('unpaid', 'Unpaid'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Credit Card'), ('debit', 'Debit Card'), ('mercado_pago', 'Mercado Pago'), ('paypal', 'PayPal')], default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user_plans', to=settings.AUTH_USER_MODEL)),
                ('plan_pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.planpricing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
