# Generated by Django 4.0.6 on 2024-01-09 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
        ('activity', '0005_alter_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_sessions', to='activity.activity'),
        ),
        migrations.AlterField(
            model_name='session',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_sessions', to='institution.space'),
        ),
    ]
