# Generated by Django 4.0.6 on 2024-01-09 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
        ('activity', '0007_alter_activity_instructor_alter_activity_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.site'),
        ),
    ]
